export type KnowledgeSource = {
  name: string;
  publisher: string;
  url: string;
};

export type ScamFlowStep = {
  stage: "接觸" | "取信" | "施壓" | "收割";
  title: string;
  description: string;
};

export type KnowledgeItem = {
  id: string;
  group: "購物交易" | "金融投資" | "身分帳號" | "人際生活" | "求職安全" | "新興科技";
  category: string;
  title: string;
  tagline: string;
  summary: string;
  cue: string;
  verify: string;
  flow: ScamFlowStep[];
  outcomes: string[];
  actions: string[];
  verificationQuestions: string[];
  sources: KnowledgeSource[];
  poster: string;
  posterAlt: string;
  reviewed: string;
};

export const knowledgeItems: KnowledgeItem[] = [
  {
    id: "customer-service",
    group: "購物交易",
    category: "假客服",
    title: "假客服解除分期",
    tagline: "ATM 不能解除扣款，先掛斷再查。",
    summary: "詐騙者掌握訂單或捐款資料後冒充客服，以重複扣款、誤設會員為由，要求操作金融交易。",
    cue: "能說出訂單不代表是真的；保持通話、操作 ATM／網銀、購買點數或交付 OTP 都是高風險要求。",
    verify: "掛斷後，從自己原本的訂單頁、卡片背面或官方網站重新取得客服電話。",
    flow: [
      { stage: "接觸", title: "冒充客服來電", description: "說出姓名、訂單或捐款紀錄，降低戒心。" },
      { stage: "取信", title: "製造帳務危機", description: "謊稱誤設分期、VIP、批發商或將連續扣款。" },
      { stage: "施壓", title: "控制操作路徑", description: "要求保持通話，轉接假銀行並操作 ATM、網銀或購買點數。" },
      { stage: "收割", title: "把轉帳說成退款", description: "實際把款項轉走，失敗時還會要求換帳戶繼續操作。" },
    ],
    outcomes: ["存款遭轉出或信用卡被盜刷", "銀行帳號、OTP 等資料外洩", "個資被用於下一波精準詐騙"],
    actions: ["立即掛斷，不依來電指示操作任何金融交易", "自行開啟原購物平台確認訂單與通知", "若已操作，立刻聯絡銀行止付並保留通聯與交易紀錄", "撥打 165 諮詢；有即時財損可報警"],
    verificationQuestions: ["官方訂單頁真的顯示相同異常嗎？", "為什麼退款需要操作 ATM 或提供 OTP？", "我能否掛斷後自己找官方客服重新聯絡？"],
    sources: [
      { name: "ATM解除分期付款詐騙", publisher: "內政部警政署刑事警察局", url: "https://www.cib.npa.gov.tw/ch/app/data/view?id=1909&module=wg116&serno=a61af506-a4ac-49eb-9c79-ef75ddc6f237" },
    ],
    poster: "/images/posters/customer-service.png",
    posterAlt: "假客服以重複扣款誘導操作 ATM，以及掛斷後自行查證的對照海報",
    reviewed: "2026-07-18",
  },
  {
    id: "investment",
    group: "金融投資",
    category: "假投資",
    title: "群組帶單與假投資平台",
    tagline: "看得到獲利，不代表領得到錢。",
    summary: "從社群廣告、交友軟體或投資群組接觸，以名師帶單和小額獲利引誘加碼，最後用各種理由阻止出金。",
    cue: "保證獲利、穩賺不賠、加私人 LINE、下載陌生投資 App、繳保證金才能出金。",
    verify: "離開群組與對方提供的網站，向合法金融機構及主管機關查詢業者資格與商品。",
    flow: [
      { stage: "接觸", title: "廣告或網友引流", description: "以股票、外匯、虛擬資產或 AI 選股吸引加入群組。" },
      { stage: "取信", title: "老師與群友演戲", description: "群組成員曬獲利，初期甚至允許小額出金。" },
      { stage: "施壓", title: "鼓勵借錢加碼", description: "假平台顯示高報酬，再以限時名額、內線消息刺激投入。" },
      { stage: "收割", title: "拒絕出金", description: "以稅金、保證金、洗碼量或 IP 異常要求繼續付款，最後關站。" },
    ],
    outcomes: ["投入本金與追加費用全部損失", "可能為加碼而貸款、負債或抵押資產", "身分證件、銀行資料被盜用", "被要求保密而與家人支持系統隔離"],
    actions: ["停止加碼，也不要再付任何解凍、稅金或保證金", "保存群組、網址、App、帳號與匯款紀錄", "聯絡銀行並撥打 165；已受害應儘速報案", "只從主管機關或合法業者名錄查證，不使用群組連結"],
    verificationQuestions: ["這個業者能在主管機關名錄中查到嗎？", "如果是真投資，為什麼保證獲利並禁止告訴家人？", "為什麼領回自己的錢還要再匯款？"],
    sources: [
      { name: "假投資話術解析與因應", publisher: "內政部警政署刑事警察局", url: "https://www.cib.npa.gov.tw/ch/app/data/view?id=1909&module=wg116&serno=a4f8d5ab-3d53-4d22-9411-031fddde7a4e" },
      { name: "虛擬資產服務商防詐規範", publisher: "金融監督管理委員會", url: "https://law.fsc.gov.tw/LawContent.aspx?id=GL004003&media=print" },
    ],
    poster: "/images/posters/investment.png",
    posterAlt: "假投資群組、假獲利平台、無法出金與向合法機構查證的流程海報",
    reviewed: "2026-07-18",
  },
  {
    id: "online-shopping",
    group: "購物交易",
    category: "假網購／包裹",
    title: "假網拍、一頁式廣告與幽靈包裹",
    tagline: "低價不是保障，訂單紀錄才是起點。",
    summary: "以超低價商品、私下交易或未下單的貨到付款包裹，騙取貨款、信用卡資料或導向假客服。",
    cue: "價格遠低於行情、永遠倒數、只用私訊、網址奇特、無公司地址、未下單卻要求取貨付款。",
    verify: "回到可信平台的訂單紀錄，查公司資料、評價、寄件人與物流官方資訊。",
    flow: [
      { stage: "接觸", title: "超低價或限量誘餌", description: "在社群、一頁式網站或私訊刊登熱門商品。" },
      { stage: "取信", title: "搬離平台私下談", description: "用假評價、盜圖、貨到付款或假第三方支付營造安全感。" },
      { stage: "施壓", title: "先付款或先取貨", description: "要求匯款、填卡號，或寄送從未下單的貨到付款包裹。" },
      { stage: "收割", title: "失聯或二次詐騙", description: "不出貨、寄劣質品，再以退款客服誘導提供更多資料。" },
    ],
    outcomes: ["付款後收不到商品或收到劣質品", "信用卡、OTP 與個資外洩", "跨境賣家失聯，消費爭議處理困難", "假退款流程造成第二次財損"],
    actions: ["使用有審核與第三方支付的可信平台，不轉私訊交易", "未下單的包裹不要取貨或付款", "商品不符時聯絡寄件人、貨運業者並使用消保申訴", "涉及詐騙或假客服時保存證據並撥打 165"],
    verificationQuestions: ["我的官方訂單紀錄中真的有這筆交易嗎？", "賣家是否有可查證的公司、地址與長期評價？", "為什麼一定要離開平台私下付款？"],
    sources: [
      { name: "假網拍詐騙話術解析", publisher: "內政部警政署刑事警察局", url: "https://www.cib.npa.gov.tw/ch/app/data/view?id=1909&module=wg116&serno=7e614f6f-df9b-4ae2-8293-ed384fb1a470" },
      { name: "一頁式廣告特徵與處理", publisher: "行政院消費者保護會", url: "https://cpc.ey.gov.tw/Page/BC16ACF0BBB9CCC2/5922d66c-3c30-4418-8ce5-29a2f09b4185" },
      { name: "幽靈包裹反詐宣導", publisher: "內政部警政署", url: "https://www.npa.gov.tw/ch/app/video/view?id=2275&module=video&serno=b2718010-a527-456b-92fa-e6c2d400c775" },
    ],
    poster: "/images/posters/online-shopping.png",
    posterAlt: "超低價網拍、私下付款、錯誤包裹與可信平台查證的流程海報",
    reviewed: "2026-07-18",
  },
  {
    id: "family-impersonation",
    group: "身分帳號",
    category: "冒名親友",
    title: "換新號碼與緊急借款",
    tagline: "語氣可以模仿，原本的聯絡方式更可靠。",
    summary: "冒充兒女、親戚或朋友，先用新號碼建立聯繫，再以急用、周轉或意外為由要求匯款。",
    cue: "新號碼、拒絕通話、急需匯款、收款人不同、要求保密或刪除舊聯絡方式。",
    verify: "用原本保存的電話回撥，或透過另一位家人確認；可事先約定不涉及個資的家庭密語。",
    flow: [
      { stage: "接觸", title: "自稱親友換號碼", description: "先問候、裝熟，誘導你自己說出對方可能是誰。" },
      { stage: "取信", title: "維持數日互動", description: "用生活對話建立熟悉感，要求更新通訊錄。" },
      { stage: "施壓", title: "突然發生急事", description: "以學費、醫療、投資周轉或事故要求立即匯款並保密。" },
      { stage: "收割", title: "匯到陌生帳戶", description: "收到錢後失聯，或再用新的緊急理由持續索款。" },
    ],
    outcomes: ["匯款難以追回", "個人與家庭資訊被用於後續冒名", "家人間信任與情緒受到傷害"],
    actions: ["不要在原對話內證明身分，先停止匯款", "使用原本電話或面對面確認", "詢問共同經歷或家庭密語，但不要傳送身分證等個資", "已匯款時立即聯絡銀行、保留紀錄並撥打 165"],
    verificationQuestions: ["我能否用原本保存的號碼聯絡本人？", "收款帳戶為什麼不是親友本人？", "對方能否回答不涉及敏感資料的共同經歷？"],
    sources: [
      { name: "猜猜我是誰話術解析", publisher: "內政部警政署刑事警察局", url: "https://www.cib.npa.gov.tw/ch/app/data/view?id=1909&module=wg116&serno=4f04dab6-3ca5-4139-a94e-66be03b62ba3" },
    ],
    poster: "/images/posters/family-impersonation.png",
    posterAlt: "冒名親友新號碼、緊急借款與使用原電話確認的流程海報",
    reviewed: "2026-07-18",
  },
  {
    id: "phishing",
    group: "身分帳號",
    category: "釣魚連結",
    title: "假物流、帳戶異常與補繳簡訊",
    tagline: "訊息可以偽造，入口要自己找。",
    summary: "假冒物流、銀行、電商、公用事業或政府機關，以配送、欠費、停權、中獎等理由誘導進入仿冒網站。",
    cue: "短網址、相似網域、倒數期限、小額補繳、要求重新登入、輸入卡號或 OTP。",
    verify: "不要使用訊息入口；直接開啟既有官方 App，或自行輸入已知官方網址與客服電話。",
    flow: [
      { stage: "接觸", title: "大量發送通知", description: "假冒包裹、公用事業、罰單、銀行或購物平台。" },
      { stage: "取信", title: "仿造官方頁面", description: "使用相似顏色、名稱與網域，讓登入或付款頁看似正常。" },
      { stage: "施壓", title: "限時輸入資料", description: "以停權、退回包裹或欠費要求卡號、密碼與 OTP。" },
      { stage: "收割", title: "接管帳戶或盜刷", description: "資料即時送給詐騙者，用於轉帳、刷卡或接管帳號。" },
    ],
    outcomes: ["信用卡遭盜刷或銀行款項被轉走", "網銀、社群或電子郵件帳號被接管", "個資遭販售並用於精準詐騙"],
    actions: ["關閉頁面，不再輸入或下載任何內容", "從官方 App 或官方帳單獨立確認", "已輸入卡號或網銀資料時立即聯絡銀行止付、停卡", "更改密碼、檢查登入紀錄，並向 165 通報可疑網址"],
    verificationQuestions: ["這個網域是否逐字符合官方網站？", "官方 App 內是否有相同通知？", "為什麼一筆小額補款需要完整卡號與 OTP？"],
    sources: [
      { name: "網購結合釣魚連結案件解析", publisher: "內政部警政署刑事警察局", url: "https://www.cib.npa.gov.tw/ch/app/news/view?id=1887&module=news&serno=26094d36-f617-40b5-9712-67b5199aac8b" },
      { name: "包裹地址錯誤釣魚簡訊", publisher: "內政部警政署警察廣播電臺", url: "https://www.pbs.npa.gov.tw/ch/app/data/view?id=18740&module=wg183&serno=fedf0c74-688b-4c94-9d5e-3fefb55cf630" },
    ],
    poster: "/images/posters/phishing.png",
    posterAlt: "假物流簡訊、仿冒登入頁、資料被竊與改從官方 App 查證的流程海報",
    reviewed: "2026-07-18",
  },
  {
    id: "account-takeover",
    group: "身分帳號",
    category: "帳號盜用",
    title: "投票連結、OTP 與帳號接管",
    tagline: "驗證碼就是鑰匙，任何人都不該索取。",
    summary: "從投票、手機送修或帳號驗證切入，取得登入資料與 OTP 後接管帳號，再冒名向親友借錢。",
    cue: "朋友傳投票連結、索取手機號碼與驗證碼、要求掃描登入碼、陌生裝置登入通知。",
    verify: "直接打電話給朋友；登入官方安全設定檢查裝置、工作階段與帳號復原資訊。",
    flow: [
      { stage: "接觸", title: "熟人帳號傳來請求", description: "請你投票、協助收驗證碼或點開看似熟悉的連結。" },
      { stage: "取信", title: "導向仿冒登入", description: "頁面要求密碼、OTP、備援碼或掃描登入碼。" },
      { stage: "施壓", title: "快速更改設定", description: "詐騙者登入後更換密碼與復原方式，把本人踢出帳號。" },
      { stage: "收割", title: "冒名擴散詐騙", description: "用你的身分向朋友借錢、索取點數或繼續傳釣魚連結。" },
    ],
    outcomes: ["帳號與私人訊息失去控制", "朋友因信任你的帳號而受騙", "相同密碼的其他服務連帶失守", "照片、聯絡人與個資外洩"],
    actions: ["立即從官方帳號復原頁重設密碼並登出其他裝置", "啟用雙重驗證，改用不同且唯一的密碼", "通知聯絡人不要相信近期訊息或付款要求", "向平台申訴並保存登入通知；涉及財損撥打 165"],
    verificationQuestions: ["我是否直接打電話確認朋友真的發出請求？", "官方服務會要求我把 OTP 傳給別人嗎？", "安全設定中是否出現陌生裝置或復原資訊？"],
    sources: [
      { name: "盜（冒）用網路帳號話術解析", publisher: "內政部警政署刑事警察局", url: "https://www.cib.npa.gov.tw/ch/app/data/view?id=1909&module=wg116&serno=a2f50753-ab28-469a-a6ce-59368758d083" },
    ],
    poster: "/images/posters/account-takeover.png",
    posterAlt: "投票連結導致帳號被接管、冒名向朋友借錢與帳號復原的流程海報",
    reviewed: "2026-07-18",
  },
  {
    id: "romance",
    group: "人際生活",
    category: "假愛情交友",
    title: "網路戀情、包裹費與投資誘導",
    tagline: "感情可以慢慢建立，匯款不必現在決定。",
    summary: "盜用照片建立長期感情與信任，再以關稅、醫療、結婚基金或共同投資為由持續索款。",
    cue: "很快示愛、身分華麗卻無法見面、要求保密、跨境包裹費、緊急周轉或帶你投資。",
    verify: "視訊也可能造假；應用多個獨立管道確認身分，並把匯款要求告訴可信任親友。",
    flow: [
      { stage: "接觸", title: "陌生人主動加好友", description: "使用盜來的俊男美女、軍官、醫師或海外工作照片。" },
      { stage: "取信", title: "密集陪伴與未來承諾", description: "每天關心、快速示愛，讓關係逐漸排除家人朋友。" },
      { stage: "施壓", title: "出現金錢難題", description: "以禮物關稅、醫療、返臺、結婚基金或投資機會索款。" },
      { stage: "收割", title: "反覆加碼後失聯", description: "每解決一個問題又出現新費用，直到無力支付或被封鎖。" },
    ],
    outcomes: ["長期、反覆的財務損失與負債", "身分資料或私密影像被掌握、威脅", "情緒創傷、羞恥感與社交隔離", "被引導進入假投資平台"],
    actions: ["沒見過且無法獨立確認的人，不匯款、不代收包裹", "把對方身分與金錢要求告訴可信任親友", "使用多個來源查照片、工作與聯絡資訊；不要只相信視訊", "停止付款、保存對話與匯款證據並撥打 165"],
    verificationQuestions: ["對方的身分能否被獨立來源證實，而不只是他提供的資料？", "為什麼每次見面前都先發生需要匯款的意外？", "我是否願意把這項匯款要求告訴家人或朋友？"],
    sources: [
      { name: "假愛情交友話術解析", publisher: "內政部警政署刑事警察局", url: "https://www.cib.npa.gov.tw/ch/app/data/view?id=1909&module=wg116&serno=064fe6c9-ae2c-40d2-a7df-2e5a4223091f" },
    ],
    poster: "/images/posters/romance.png",
    posterAlt: "網路戀情建立信任、以包裹或投資索款，以及找親友共同查證的流程海報",
    reviewed: "2026-07-18",
  },
  {
    id: "government-impersonation",
    group: "身分帳號",
    category: "假冒檢警／機關",
    title: "假公文、偵查不公開與監管帳戶",
    tagline: "檢警不會電話辦案，也沒有監管帳戶。",
    summary: "假冒戶政、健保、電信或醫院，再轉接假警察與檢察官，以涉案恐懼與偵查不公開控制被害人。",
    cue: "電話做筆錄、傳假公文、要求保密、監管帳戶、交付金融卡，或把卡片／現金放在指定地點。",
    verify: "掛斷後自己查機關總機並重新撥打；司法案件會以正式通知要求到案，不會電話監管財產。",
    flow: [
      { stage: "接觸", title: "假機關通知身分遭冒用", description: "自稱戶政、醫院、健保、電信或銀行，聲稱你涉入異常。" },
      { stage: "取信", title: "一條龍轉接假檢警", description: "提供姓名、職稱、假案號與偽造公文，營造正式感。" },
      { stage: "施壓", title: "恐嚇並切斷求助", description: "以洗錢罪、拘票、偵查不公開要求全天回報、不得告訴家人。" },
      { stage: "收割", title: "接管所有財產", description: "要求匯入監管帳戶、交卡、現金或貴重物，甚至利用帳戶洗錢。" },
    ],
    outcomes: ["畢生積蓄、金融卡與帳戶遭掏空", "帳戶被利用接收不明金流", "在長時間恐嚇下產生嚴重心理壓力", "個資與財產狀況完全暴露"],
    actions: ["立即掛斷，不接受來電者代為轉接任何機關", "自行查詢該機關官方總機再確認", "不交付金融卡、密碼、現金，也不把物品放在門外", "撥打 165；有人身或即時取款危險時撥打 110"],
    verificationQuestions: ["為什麼警方要用電話做筆錄並要求保密？", "官方機關是否真的有『監管帳戶』這種程序？", "我能否掛斷後自己撥官方總機確認案號？"],
    sources: [
      { name: "假冒機構（公務員）話術解析", publisher: "內政部警政署刑事警察局", url: "https://www.cib.npa.gov.tw/ch/app/data/view?id=1909&module=wg116&serno=b7cf505d-f709-4885-b06b-d29b092ce04f" },
    ],
    poster: "/images/posters/government-impersonation.png",
    posterAlt: "假機關轉接假檢警、偽造公文、監管帳戶與掛斷查官方總機的流程海報",
    reviewed: "2026-07-18",
  },
  {
    id: "job-scam",
    group: "求職安全",
    category: "求職／打工詐騙",
    title: "高薪工作、保證金與人頭帳戶",
    tagline: "找工作是領薪水，不是先交錢與帳戶。",
    summary: "以高薪、輕鬆、海外工作或代購為誘餌，收取費用、取得金融帳戶，嚴重時可能控制人身自由。",
    cue: "私人帳號徵才、工作內容不清、先繳保證金／治裝費、代收款、交金融卡、申辦約定帳戶或出國高薪。",
    verify: "查公司登記、地址、公開電話與職缺內容；面試前告知家人行程並遵守勞動部三要七不。",
    flow: [
      { stage: "接觸", title: "高薪低門檻廣告", description: "在社群或私訊刊登輕鬆打工、代購、刷單或海外工作。" },
      { stage: "取信", title: "非正式面試與合約", description: "快速錄取，以培訓、薪資轉帳或公司規定包裝異常要求。" },
      { stage: "施壓", title: "索取錢與金融工具", description: "要求費用、證件、存摺、提款卡、網銀密碼或設定約定轉帳。" },
      { stage: "收割", title: "帳戶犯罪或人身控制", description: "帳戶成為詐騙金流工具，或被帶往陌生地點、限制自由。" },
    ],
    outcomes: ["保證金、訓練費等財務損失", "銀行帳戶成為人頭帳戶並面臨法律風險", "身分證件被冒用", "海外或封閉地點可能涉及拘禁與人身危險"],
    actions: ["不繳不合理費用，不交金融卡、存摺、密碼或個人證件正本", "面試前查公司並告知家人地點、時間與聯絡人", "不簽看不懂或不讓你保留副本的合約", "感到受控立即離開並撥 110；可疑徵才撥 165 或洽勞動機關"],
    verificationQuestions: ["公司登記、地址與公開電話是否一致？", "正常工作為什麼需要我的提款卡或先繳錢？", "家人是否知道我的面試地點與聯絡方式？"],
    sources: [
      { name: "假求職話術解析", publisher: "內政部警政署刑事警察局", url: "https://www.cib.npa.gov.tw/ch/app/data/view?id=1909&module=wg116&serno=87a85079-c42f-48cb-9506-14e08c912a39" },
      { name: "求職防騙與三要七不", publisher: "勞動部", url: "https://www.mol.gov.tw/1607/28690/87756/87759/lpsimplelist" },
    ],
    poster: "/images/posters/job-scam.png",
    posterAlt: "高薪徵才、收取費用與帳戶、可能人身危險及安全面試查證的流程海報",
    reviewed: "2026-07-18",
  },
  {
    id: "loan-scam",
    group: "金融投資",
    category: "貸款／人頭帳戶",
    title: "保證過件、預收費用與刷流水",
    tagline: "貸款不是交出帳戶，更不能製造假金流。",
    summary: "冒充銀行或融資公司，利用急需資金的壓力，以保證過件吸引申貸，再索取費用、證件與帳戶控制權。",
    cue: "不看信用保證過件、放款前先繳費、寄提款卡、提供網銀、製造帳戶金流、代辦自然人憑證。",
    verify: "只透過合法金融機構官方電話與據點申辦，查清契約、利率、費用與業者資格。",
    flow: [
      { stage: "接觸", title: "保證過件廣告", description: "鎖定急需用錢或信用條件不佳者，宣稱快速放款。" },
      { stage: "取信", title: "假冒合法機構", description: "使用相似名稱、Logo、證件與合約，搭配金融術語。" },
      { stage: "施壓", title: "先付費或交帳戶", description: "要求手續費、保證金、提款卡、網銀，或用『刷流水』美化信用。" },
      { stage: "收割", title: "拿錢失聯並利用帳戶", description: "貸款不會入帳，帳戶反而被用於詐騙金流與洗錢。" },
    ],
    outcomes: ["預繳費用與保證金損失", "證件遭冒用申辦服務或貸款", "帳戶遭警示、凍結或成為人頭帳戶", "可能捲入詐欺、洗錢等法律程序"],
    actions: ["停止付款與交付帳戶，改由官方銀行管道申請", "不寄金融卡、不交密碼、不配合製造金流", "逐條閱讀契約並保留副本；不懂就找可信任專業人士", "已交付資料或帳戶時立刻通知銀行、報警並撥 165"],
    verificationQuestions: ["這家業者能否從官方金融機構名錄與電話查到？", "為什麼放款前要先匯保證金或寄金融卡？", "所謂刷流水是否可能讓我的帳戶接收不明款項？"],
    sources: [
      { name: "貸款詐欺之樣態、危害與防範", publisher: "臺灣臺北地方檢察署", url: "https://www.tpc.moj.gov.tw/292885/976681/661783/1362145/post" },
      { name: "防制貸款詐騙與人頭帳戶", publisher: "中華郵政", url: "https://www.post.gov.tw/post/internet/Anti-Fraud/index.jsp" },
    ],
    poster: "/images/posters/loan-scam.png",
    posterAlt: "保證過件貸款、預收費用、交付帳戶造成財務與法律風險的流程海報",
    reviewed: "2026-07-18",
  },
  {
    id: "rental-scam",
    group: "人際生活",
    category: "租屋詐騙",
    title: "低價好房與看屋前訂金",
    tagline: "先看屋、查身分、讀契約，再付款。",
    summary: "盜用漂亮房屋照片與低於行情租金吸引詢問，假房東以人在外地、多人搶租為由要求看屋前付款。",
    cue: "租金明顯過低、無法看屋、要求先付訂金、拒絕出示身分與所有權資料、只用通訊軟體聯繫。",
    verify: "實際看屋，核對房東身分、房屋所有權或合法授權，確認租約內容後再付款。",
    flow: [
      { stage: "接觸", title: "盜圖刊登低價好房", description: "用熱門地段、精美照片與低租金吸引學生或急租者。" },
      { stage: "取信", title: "假房東編造理由", description: "聲稱人在外地、委託親友，或已有多人排隊。" },
      { stage: "施壓", title: "看屋前先付訂金", description: "要求保留金、押金或首月租金，承諾付款後交鑰匙。" },
      { stage: "收割", title: "收款後消失", description: "地址不存在、無法入住，或同一物件被重複出租給多人。" },
    ],
    outcomes: ["訂金、押金與租金損失", "開學或搬遷時無處可住", "身分證與財力資料遭冒用", "與真正屋主產生爭議"],
    actions: ["未看屋、未查驗身分與權利前不付款", "核對房東身分證、所有權資料或正式授權", "使用可追溯的平台，保留廣告、對話、契約與付款紀錄", "發現受騙立即聯絡銀行、平台、警方與 165"],
    verificationQuestions: ["我是否實際進入房屋並確認屋況？", "出租人能否證明是屋主或有合法授權？", "租金低於行情的理由是否能被獨立查證？"],
    sources: [
      { name: "租屋詐騙：付訂金才能看房", publisher: "內政部警政署警察廣播電臺", url: "https://www.pbs.npa.gov.tw/ch/app/data/view?id=18740&module=wg183&serno=0963ac01-b7c4-4eb3-a988-2fce4d076e67" },
    ],
    poster: "/images/posters/rental-scam.png",
    posterAlt: "低價租屋、看屋前訂金、假房東失聯與核對屋主身分契約的流程海報",
    reviewed: "2026-07-18",
  },
  {
    id: "ticket-scam",
    group: "購物交易",
    category: "門票／票券詐騙",
    title: "社群轉售、假按鈕與實名認證",
    tagline: "搶票越急，越要確認網域與售票管道。",
    summary: "利用熱門活動的稀缺與時間壓力，假冒賣家、投放仿冒導覽按鈕或提供假售票與假客服網站。",
    cue: "公關票、內部票、先匯訂金、假第三方平台、實名認證失敗、要求網銀操作或提供卡號 OTP。",
    verify: "只從主辦單位公布的官方售票入口購買，逐字確認網域，不使用陌生人提供的客服連結。",
    flow: [
      { stage: "接觸", title: "熱門票券與假廣告", description: "在社群轉售稀有門票，或在售票頁投放像『下一步』的廣告。" },
      { stage: "取信", title: "偽造票券與交易平台", description: "展示假訂單、假身分，導向仿冒售票或第三方金流頁。" },
      { stage: "施壓", title: "搶票倒數與驗證", description: "以名額即將消失、實名失敗要求立即付款、登入或聯絡假客服。" },
      { stage: "收割", title: "無票、盜刷或連續轉帳", description: "收款後封鎖，或取得卡號、OTP 後進行盜刷與多次轉帳。" },
    ],
    outcomes: ["付款後沒有票或拿到無效票券", "信用卡與帳戶遭盜刷、轉出", "身分證影像被用於偽造或其他詐騙", "錯過活動並難以向私人賣家求償"],
    actions: ["從主辦單位官方頁進入售票系統，不從廣告或私訊進入", "不向陌生人私下匯款，也不做所謂金流／實名驗證", "輸入卡號前逐字確認網域與頁面是否跳轉", "已輸入金融資料立即聯絡銀行；保存證據並撥 165"],
    verificationQuestions: ["這個入口是否由主辦單位官方頁直接連出？", "廣告按鈕旁是否標示贊助或外部網站？", "為什麼買票需要向陌生客服操作網銀驗證？"],
    sources: [
      { name: "假按鈕盜刷票券詐騙", publisher: "內政部警政署刑事警察局", url: "https://www.cib.npa.gov.tw/ch/app/news/view?id=1887&module=news&serno=f2131775-f260-456b-bf77-8fb1a9158b5e" },
      { name: "社團群組買票詐騙", publisher: "內政部警政署刑事警察局", url: "https://www.cib.npa.gov.tw/ch/app/news/view?id=1887&module=news&serno=00fd79a0-946e-4bb6-8df4-0e9f6b48da79" },
    ],
    poster: "/images/posters/ticket-scam.png",
    posterAlt: "社群門票、假售票按鈕、信用卡被盜與改用官方售票平台的流程海報",
    reviewed: "2026-07-18",
  },
  {
    id: "deepfake",
    group: "新興科技",
    category: "AI 深偽詐騙",
    title: "仿造聲音、視訊與人物身分",
    tagline: "看見本人、聽見聲音，也要換管道查證。",
    summary: "利用公開影音合成親友、主管、老師、官員或名人的聲音與影像，在視訊或語音中提出金錢與資料要求。",
    cue: "突然換聯絡方式、聲音或畫面細節不自然、拒絕延後、急要匯款／OTP、要求保密，或對動態問題答非所問。",
    verify: "使用早已保存的聯絡方式回撥、面對面確認，並使用事先約定的家庭或團隊驗證語。",
    flow: [
      { stage: "接觸", title: "蒐集公開影音", description: "從社群影片、直播、錄音取得臉部與聲音素材。" },
      { stage: "取信", title: "合成逼真的通話", description: "製作仿真人語音、短影片或即時視訊，冒充熟人與權威。" },
      { stage: "施壓", title: "用急事阻止思考", description: "聲稱事故、機密任務或帳號異常，要求匯款、密碼、私密資訊或 OTP。" },
      { stage: "收割", title: "在查證前完成交易", description: "一旦付款或交出資料就切斷聯繫，也可能拿你的影音再冒充你。" },
    ],
    outcomes: ["因相信聲音或臉孔而快速匯款", "密碼、OTP 與私密資訊外洩", "個人影音被持續用於冒名與擴散詐騙", "家庭或組織內部信任受到破壞"],
    actions: ["不要在原通話內完成付款或提供敏感資料", "用已知電話回撥，或找另一位可信任者交叉確認", "使用事先約定且不公開的驗證語，詢問臨時動態問題", "保留影音與帳號資訊，撥 165；帳戶受影響立刻聯絡銀行"],
    verificationQuestions: ["我能否用原本保存的號碼回撥本人？", "對方能否回答一個臨時、非公開且不涉及個資的問題？", "這項要求即使由本人提出，是否仍不符合平常流程？"],
    sources: [
      { name: "AI 深偽詐騙宣導", publisher: "內政部警政署", url: "https://www.npa.gov.tw/ch/app/video/view?id=2275&module=video&serno=3328b46f-c588-44c9-a1fa-9f54adcade3f" },
    ],
    poster: "/images/posters/deepfake.png",
    posterAlt: "AI 仿造視訊與聲音、急迫匯款要求及改用原電話和面對面確認的流程海報",
    reviewed: "2026-07-18",
  },
  {
    id: "qr-payment",
    group: "新興科技",
    category: "QR／付款碼詐騙",
    title: "付款碼、無卡提款與畫面分享",
    tagline: "付款碼不是收款證明，而可能是花錢的鑰匙。",
    summary: "假買家或假客服要求翻拍、截圖或視訊分享付款碼、無卡提款序號，讓詐騙者直接消費或提領。",
    cue: "買家說無法付款、客服要求金流驗證、分享付款碼截圖、無卡提款碼、掃描陌生碼或共享銀行畫面。",
    verify: "只在自己開啟的官方銀行／支付 App 內確認收款；任何支付或提款憑證都不傳給別人。",
    flow: [
      { stage: "接觸", title: "假買家表示交易失敗", description: "在網拍或社群接洽賣家，聲稱無法下單或付款。" },
      { stage: "取信", title: "引導聯絡假客服", description: "客服以實名、金流或帳戶認證解釋操作必要性。" },
      { stage: "施壓", title: "要求分享支付憑證", description: "要求截圖、翻拍、共享畫面，取得付款碼或無卡提款憑證。" },
      { stage: "收割", title: "快速消費或提款", description: "憑證如同現金鑰匙，詐騙者可在極短時間扣款或提領。" },
    ],
    outcomes: ["帳戶款項被立即消費或無卡提領", "詐騙者要求連續產生多組憑證擴大損失", "網銀畫面與帳戶資訊外洩", "可能再被誘導寄現金或購買點數"],
    actions: ["不截圖、不翻拍、不分享任何付款碼或無卡提款資訊", "中止與假客服的通話或視訊，只從官方 App 查看交易", "憑證已外流時立即聯絡銀行／支付機構凍結功能", "保存對話、帳號與時間並撥打 165；已提領則報警"],
    verificationQuestions: ["我是收款方，為什麼需要提供能付款或提款的憑證？", "官方 App 是否真的顯示收款失敗或需要認證？", "這個碼若被別人取得，是否就能直接動用我的錢？"],
    sources: [
      { name: "付款碼及無卡提款 QR Code 設局", publisher: "內政部警政署刑事警察局", url: "https://www.cib.npa.gov.tw/ch/app/news/view?id=1887&module=news&serno=d84819b1-a785-47cf-a84c-82274f6db300" },
    ],
    poster: "/images/posters/qr-payment-v2.png",
    posterAlt: "假買家索取不可掃描的抽象付款碼、資金被提領與拒絕分享憑證的流程海報",
    reviewed: "2026-07-18",
  },
];
